/**
 * The app WebView points somewhere. Make sure it points at the real site.
 *
 * WHY THIS EXISTS
 *
 * This is the single most destructive mistake available in this project, and it
 * had already been made. ios/App/App/capacitor.config.json contained:
 *
 *     "url": "https://www.wesuplusly.com/"
 *
 * — an extra "ly". Every iOS build would have launched a WebView on a domain
 * that does not resolve: a permanently white screen, no error dialog, no log
 * anyone would read. And it was invisible, because Android's copy of the same
 * file was correct, the APK was built and tested and appeared to work, and
 * capacitor.config.ts in the repo root was correct. The wrong value lived only
 * in the untracked generated file the iOS build actually reads.
 *
 * WHAT IS AND IS NOT CHECKED — and the mistake that broke a deploy
 *
 * The two native copies are GENERATED by `npx cap sync` and are gitignored
 * (ios/.gitignore, android/.gitignore). They exist on a developer machine that
 * has run the sync. They do NOT exist in a fresh clone, and they do not exist
 * on Vercel, which has no Android or iOS toolchain.
 *
 * The first version of this gate treated "generated copy absent" as a failure.
 * That broke the web deployment on Vercel with:
 *
 *     FAIL ios/App/App/capacitor.config.json is missing
 *     FAIL android/app/src/main/assets/capacitor.config.json is missing
 *
 * A gate that cannot tell "absent by design" from "broken" is worse than no
 * gate, because it takes the site down and teaches people to ignore it.
 *
 * So the rule is now:
 *
 *   capacitor.config.ts — the SOURCE OF TRUTH — must always exist and be valid.
 *   Generated copies    — checked ONLY if they are present. Their absence is
 *                          normal and never a failure; their presence is the
 *                          exact condition under which drift goes unnoticed, so
 *                          that is when comparing them earns its keep.
 *
 * Usage: node scripts/check-app-url.mjs
 */
import { readFileSync, existsSync } from "node:fs";

/** The only file that is committed. Everything else is generated from it. */
const SOURCE = "capacitor.config.ts";

/** Generated by `npx cap sync`, gitignored, absent on a fresh clone and on CI. */
const GENERATED = [
  "ios/App/App/capacitor.config.json",
  "android/app/src/main/assets/capacitor.config.json",
];

/** Pull the server url out of a TS or JSON config without a parser. */
function serverUrl(path) {
  const raw = readFileSync(path, "utf8");
  const m = /["']?url["']?\s*:\s*["'](https?:\/\/[^"']+)["']/.exec(raw);
  return m?.[1] ?? null;
}

const problems = [];
const checked = [];

// --- the source of truth: mandatory
if (!existsSync(SOURCE)) {
  problems.push(`${SOURCE} is missing — there is no source of truth to check`);
} else {
  const url = serverUrl(SOURCE);
  if (!url) {
    problems.push(`${SOURCE} has no server.url — the app would fall back to bundled files`);
  } else {
    checked.push({ path: SOURCE, url });
  }
}

// --- generated copies: only when present
const present = GENERATED.filter((p) => existsSync(p));
const absent = GENERATED.filter((p) => !existsSync(p));
for (const path of present) {
  const url = serverUrl(path);
  if (!url) {
    problems.push(`${path} exists but has no server.url — run \`npx cap sync\` to regenerate it`);
    continue;
  }
  checked.push({ path, url });
}

// --- all copies that exist must agree
const distinct = [...new Set(checked.map((c) => c.url))];
if (distinct.length > 1) {
  problems.push(
    `the app points at different hosts in different places:\n` +
      checked.map((c) => `        ${c.url}   (${c.path})`).join("\n") +
      `\n      One of these is wrong and the build will show a white screen on that platform.`,
  );
}

// A typo'd host still parses as a URL, so also require a plausible domain. A
// doubled letter before the TLD is the signature of a hand-edit typo, and the
// registrable name must be real.
for (const { path, url } of checked) {
  const host = new URL(url).hostname;
  if (!/^www\.[a-z0-9-]+\.[a-z]{2,}$/.test(host)) {
    problems.push(`${path}: host "${host}" does not look like a real domain`);
  }
  if (/(.)\1{2,}\.[a-z]{2,}$/.test(host)) {
    problems.push(`${path}: host "${host}" has a suspicious repeated letter before the TLD`);
  }
}

console.log(`  the app loads ${distinct[0] ?? "(nothing)"}`);
for (const { path, url } of checked) console.log(`    ${url}   ${path}`);
if (absent.length) {
  console.log(
    `    (${absent.length} generated cop${absent.length === 1 ? "y is" : "ies are"} absent — ` +
      `not built on this machine, so nothing to compare)`,
  );
}

if (problems.length) {
  for (const p of problems) console.error(`  FAIL ${p}`);
  console.error("\n  the app would launch on the wrong site");
  process.exit(1);
}
console.log(
  checked.length > 1
    ? "  android and iOS load the same production site"
    : "  the configured host is the production site",
);
