// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const envObj = ((globalThis as any).__env__ ?? {}) as Record<string, string | undefined>;
    const SUPABASE_URL = process.env.SUPABASE_URL || envObj.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || envObj.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);

/**
 * Populate the caller's identity when there is one, but never reject.
 *
 * For pages that must render something for both a signed-in listener and an
 * anonymous visitor — a shared playlist, for instance. `requireSupabaseAuth`
 * throws with no Authorization header, which would lock anonymous visitors out
 * of the public editorial playlists entirely.
 *
 * context.supabase is always an RLS-scoped client bound to the caller's token,
 * so handlers must treat `userId === null` as "anonymous" and not assume an
 * owner.
 */
export const optionalSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const envObj = ((globalThis as any).__env__ ?? {}) as Record<string, string | undefined>;
    const SUPABASE_URL = process.env.SUPABASE_URL || envObj.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || envObj.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      throw new Error(`Missing Supabase environment variable(s): ${missing.join(", ")}`);
    }

    const request = getRequest();
    const authHeader = request?.headers?.get("authorization") ?? null;
    const token =
      authHeader && authHeader.startsWith("Bearer ") ? authHeader.replace("Bearer ", "") : null;
    const usableToken = token && token.split(".").length === 3 ? token : null;

    // Always build a client, so context.supabase has one type whether or not a
    // session was presented. With no usable token it is an anonymous client and
    // RLS decides what it may read — which is exactly what an anonymous visitor
    // is entitled to.
    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: usableToken ? { Authorization: `Bearer ${usableToken}` } : undefined,
      },
      auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
    });

    // A token that fails verification is treated as anonymous rather than as an
    // error: the visitor still gets the public view instead of a thrown
    // "Unauthorized".
    let userId: string | null = null;
    let claims: Record<string, unknown> | null = null;
    if (usableToken) {
      const { data, error } = await supabase.auth.getClaims(usableToken);
      if (!error && data?.claims?.sub) {
        userId = data.claims.sub;
        claims = data.claims as Record<string, unknown>;
      }
    }

    // One next() call, one context type. Multiple calls with different literal
    // shapes made the middleware's own type unresolvable.
    return next({ context: { supabase, userId, claims } });
  },
);
